### ISSUE TITLE
 error: Build input files cannot be found: 

### ISSUE THREAD

**Issue by cristea2017** [acotilla91/Muvis#1]
<img width="1138" alt="Captură de ecran din 2021-07-23 la 21 04 30" src="https://user-images.githubusercontent.com/28201006/126823150-299fdc3a-c751-44d5-826d-9f1daa7b9781.png">

**Comment by acotilla91** [comment]
The app has submodules, you just need to sync/pull the submodules.

Since you likely cloned the repo without the `--recurse-submodules` command, you can go with the alternative, please run these two commands:

```
git submodule init
git submodule update
```

More info here: https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by cristea2017** [comment]
thanks
